### ISSUE TITLE
Volume

### ISSUE THREAD

**Issue by yeoniii20** [yeoniii20/goraebab_web#19]
# Todo 🚕

> network feedback 반영 및 style 수정 + volume 개발

### network 및 container 추가 구현 사항 🚀

- [ ] container에 image 띄우기 기능
- [x] 컨테이너 개 수 제한 및 scroll 생성
- [x] host 하단 container section 밀림 현상 수정
- [x] host 삭제
- [x] network (bridge) 삭제
- [ ] network 내 container 분리
- [ ] network 내 container 삭제

### volume 새로운 기능 구현 사항 🚛

- [x] volume 추가 기능
- [ ] 설계도에 volume 표시
